version: '3.8'

services:
  codeshare_web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR_NAME=VALUE
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # removed --reload for production
    restart: always

  redis:
    image: redis:latest
    command: redis-server --bind 0.0.0.0

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ../nginx/certbot/www:/var/www/certbot/:ro
      - ../nginx/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
      - certbot
    restart: always

  certbot:
    image: certbot/certbot:latest
    command: renew
    volumes:
      - ../nginx/certbot/www/:/var/www/certbot/:rw
      - ../nginx/certbot/conf/:/etc/letsencrypt/:rw